# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    tags:
      - 'v*'

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-publish-project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x.x' # SDK Version to use; x will use the latest version of the 3.1 channel
      - run: dotnet build HappyLittleHelpers.AdhocDataQueries.csproj
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\v//}" >> $GITHUB_ENV
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: HappyLittleHelpers.AdhocDataQueries.csproj
          VERSION_STATIC: ${{ env.TAG }}
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org